import { motion } from 'framer-motion';
import { HiDownload, HiHeart } from 'react-icons/hi';

export default function Gallery() {
  const images = [
    { src: '/cyberpunk_city.png', title: 'Cyberpunk Metropolis', style: 'Col 1 Span 1' },
    { src: '/magic_forest.png', title: 'Enchanted Forest', style: 'Col 2 Span 2' },
    { src: '/neon_car.png', title: 'Neon Racing', style: 'Col 3 Span 1' },
    { src: '/astronaut_cat.png', title: 'Cosmic Feline', style: 'Col 1 Span 2' },
    { src: '/cyber_samurai.png', title: 'Neo Shogun', style: 'Col 3 Span 2' },
    { src: '/chibi_robot.png', title: 'Companion Bot', style: 'Col 2 Span 1' },
  ];

  return (
    <section id="gallery" className="py-24 border-t border-[var(--border)]">
      <div className="max-w-7xl mx-auto px-6 lg:px-8">
        {/* Section Header */}
        <div className="text-center max-w-3xl mx-auto mb-16">
          <h2 className="text-3xl sm:text-4xl font-extrabold tracking-tight text-[var(--text-h)] mb-4">
            See What's Possible
          </h2>
          <p className="text-lg text-[var(--text)]">
            Generated by our community of artists and engineers.
          </p>
        </div>

        {/* Gallery Grid/Masonry */}
        <div className="columns-1 sm:columns-2 lg:columns-3 gap-6 space-y-6">
          {images.map((img, index) => (
            <motion.div
              key={index}
              initial={{ opacity: 0, y: 40 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true, margin: '-50px' }}
              transition={{ duration: 0.6, delay: index * 0.05 }}
              className="break-inside-avoid relative overflow-hidden rounded-3xl group cursor-pointer border border-[var(--border)] shadow-md shadow-black/[0.02]"
            >
              <img
                src={img.src}
                alt={img.title}
                loading="lazy"
                className="w-full object-cover transition-transform duration-500 ease-out group-hover:scale-105"
              />

              {/* Hover Overlay */}
              <div className="absolute inset-0 bg-gradient-to-t from-black/80 via-black/30 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300 flex flex-col justify-end p-6">
                <div className="text-white">
                  <span className="text-xs uppercase tracking-widest text-[var(--accent)] font-semibold mb-1 block">
                    Branded Style
                  </span>
                  <h4 className="text-lg font-bold mb-3">{img.title}</h4>
                  <div className="flex items-center gap-4 text-sm text-gray-300">
                    <button className="flex items-center gap-1 hover:text-white transition-colors">
                      <HiHeart /> 1.2k
                    </button>
                    <button className="flex items-center gap-1 hover:text-white transition-colors">
                      <HiDownload /> Remix
                    </button>
                  </div>
                </div>
              </div>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
}
